DROP TABLE CLIMATE_DISASTER;
DROP TABLE DISASTER;
DROP TABLE COUNTRY;
DROP TABLE SUB_REGION;
DROP TABLE REGION;

--CREATE DES TABLES DE LA BDD--

CREATE TABLE REGION (region_code INT PRIMARY KEY, name VARCHAR NOT NULL);

CREATE TABLE SUB_REGION (sub_region_code INT PRIMARY KEY, name VARCHAR NOT NULL, region_code INT REFERENCES REGION (region_code) ON DELETE SET NULL);

CREATE TABLE COUNTRY (country_code INT PRIMARY KEY, name VARCHAR NOT NULL, ISO2 CHAR(2), ISO3 CHAR(3), sub_region_code INT REFERENCES SUB_REGION (sub_region_code) ON DELETE SET NULL);

CREATE TABLE DISASTER (disaster_code SERIAL PRIMARY KEY, disaster VARCHAR NOT NULL);

CREATE TABLE CLIMATE_DISASTER (country_code INT REFERENCES COUNTRY (country_code) ON DELETE CASCADE, disaster_code INT REFERENCES DISASTER (disaster_code) ON DELETE CASCADE, year INT, number INT);

ALTER TABLE CLIMATE_DISASTER  ADD CONSTRAINT CLIMATE_DISASTER_pkey PRIMARY KEY (country_code,disaster_code,year);
